spring:
  application:
    name: ms-compte
  datasource:
    url: jdbc:mysql://localhost:3306/compte_db_test?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    inetutils:
      prefer-hostname-over-ip: true
server:
  port: 8081

logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/