spring:
  application:
    name: ms-compte  # Nom du service
  datasource:
    url: jdbc:mysql://localhost:3306/compte_db_test?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Permet à ce service de récupérer le registre des services
    register-with-eureka: true  # Permet à ce service de s'enregistrer auprès d'Eureka
